name: 'Setup Applanga CLI action'
description: 'Setup Applanga command line tool'
inputs:
  version:
    description: 'Applanga cli version'
    required: true
branding:
  icon: 'map-pin'  
  color: 'blue'
runs:
  using: 'node12'
  main: 'index.js'
